/**
 * DevsFireClient.ts
 * ─────────────────────────────────────────────────────────────────────────────
 * Blazen Sim – DEVS-FIRE simulation API client service.
 *
 * Responsibilities (Single Responsibility: DEVS-FIRE API communication):
 *  - Acquire a dynamic session token by POSTing to /api/connectToServer.
 *  - Append that token as ?userToken=TOKEN on every subsequent API call.
 *  - Push simulation parameters to the engine (setMultiParameters).
 *  - Trigger execution and poll for results (runSimulation).
 *
 * Authentication flow (DEVS-FIRE specific):
 *  1. POST /api/connectToServer  →  response body is the userToken string.
 *  2. All further requests include ?userToken=<token> as a query parameter.
 *     No Authorization header is used.
 * ─────────────────────────────────────────────────────────────────────────────
 */

import type { SimulationParams } from './ClaudeAgentService';

// ── Types ────────────────────────────────────────────────────────────────────

/** Shape of DEVS-FIRE's simulation result payload */
export interface SimulationResult {
  sessionId: string;
  status: 'completed' | 'failed' | 'timeout';
  /** GeoJSON FeatureCollection or proprietary fire-perimeter data */
  firePerimeter?: Record<string, unknown>;
  /** Cell-level data parsed from DEVS-FIRE output for the thermal renderer */
  thermalGrid?: ThermalCell[];
  /** Human-readable summary generated by DEVS-FIRE */
  summary?: string;
  /** Any error message surfaced by DEVS-FIRE */
  errorDetail?: string;
  /** Grid width (columns) returned by DEVS-FIRE – needed for cell-ID mapping */
  gridWidth?: number;
  /** Grid height (rows) returned by DEVS-FIRE */
  gridHeight?: number;
  /** Cell IDs on the active fire perimeter at the end of the simulation */
  perimeterCellIds?: number[];
  /** Raw DEVS-FIRE burning-cells result string (cellId,ignitionTime pairs) */
  rawBurningCells?: string;
  /** Raw DEVS-FIRE perimeter-cells result string (space/comma-separated cell IDs) */
  rawPerimeterCells?: string;
}

/** Represents a single cell in the DEVS-FIRE thermal output grid */
export interface ThermalCell {
  /** Column index in the simulation grid */
  col: number;
  /** Row index in the simulation grid */
  row: number;
  /** Normalised fire intensity in range [0.0, 1.0] (1.0 for all burning cells) */
  intensity: number;
  /** Ignition time returned by DEVS-FIRE (simulation seconds from start) */
  timeOffsetSeconds: number;
  /** True when this cell is on the active fire perimeter */
  isPerimeter?: boolean;
}

// ── Service class ─────────────────────────────────────────────────────────────

export class DevsFireClient {
  /** Base URL of the DEVS-FIRE REST API */
  private readonly baseUrl: string;

  /** Default timeout for DEVS-FIRE requests in milliseconds */
  private readonly timeoutMs: number;

  constructor() {
    this.baseUrl = process.env.DEVS_FIRE_BASE_URL ?? 'https://firesim.cs.gsu.edu';
    this.timeoutMs = parseInt(process.env.DEVS_FIRE_TIMEOUT_MS ?? '30000', 10);
  }

  // ── Public interface ────────────────────────────────────────────────────────

  /**
   * runFullSimulation
   * ─────────────────────────────────────────────────────────────────────────
   * Orchestrates the actual DEVS-FIRE lifecycle (discovered from server source):
   *   1. loginToServer     – POST /api/v1/auth/login → JWT Bearer token
   *   2. buildIgnitionPlan – convert Claude params into DEVS-FIRE payload
   *   3. runSimulationJWT  – POST /simulation with Bearer token
   *   4. parseBurningEvents– convert [{op,x,y}] array → ThermalCell[]
   *
   * @param params – Extracted simulation parameters from ClaudeAgentService.
   * @returns        The completed SimulationResult from DEVS-FIRE.
   */
  async runFullSimulation(params: SimulationParams): Promise<SimulationResult> {
    const jwtToken = await this.loginToServer();
    const plan = this.buildIgnitionPlan(params);
    const result = await this.runSimulationJWT(jwtToken, plan);
    return result;
  }

  /**
   * loginToServer
   * POST /api/v1/auth/login → JWT token string.
   * Credentials are read from DEVS_FIRE_EMAIL / DEVS_FIRE_PASSWORD env vars.
   */
  async loginToServer(): Promise<string> {
    const email    = process.env.DEVS_FIRE_EMAIL;
    const password = process.env.DEVS_FIRE_PASSWORD;

    if (!email || !password) {
      throw new Error(
        '[DevsFireClient] DEVS_FIRE_EMAIL and DEVS_FIRE_PASSWORD must be set in the environment.'
      );
    }

    const res = await this.fetchWithTimeout(`${this.baseUrl}/api/v1/auth/login`, {
      method: 'POST',
      headers: {
        'Content-Type': 'application/json',
        'Origin': this.baseUrl,
      },
      body: JSON.stringify({ email, password }),
    });

    if (!res.ok) {
      const body = await res.text();
      throw new Error(`[DevsFireClient] Login failed (${res.status}): ${body}`);
    }

    const data = (await res.json()) as { token?: string };
    if (!data.token) {
      throw new Error('[DevsFireClient] Login response did not contain a token.');
    }

    console.info('[DevsFireClient] JWT token acquired.');
    return data.token;
  }

  /**
   * buildIgnitionPlan
   * Converts Claude-extracted SimulationParams into the DEVS-FIRE ignition
   * plan JSON format expected by POST /simulation.
   *
   * Defaults mirror the QBird30 sample bundled in the DEVS-FIRE frontend:
   *  - 200×200 grid, 30 m cell resolution
   *  - Centre point: Atlanta area (EPSG:5070 projection)
   *  - Single continuous ignition segment through grid centre
   */
  buildIgnitionPlan(params: SimulationParams): Record<string, unknown> {
    const GRID = 200;
    const cx   = Math.floor(GRID / 2);     // grid centre column
    const cy   = Math.floor(GRID / 2);     // grid centre row

    // Wind speed: Claude provides mph, DEVS-FIRE uses m/s (1 mph = 0.44704 m/s)
    const windSpeed = params.windSpeed != null
      ? Math.round(params.windSpeed * 0.44704 * 100) / 100
      : 0.6;

    // windDirection from spec (0=South, 90=West, 180=North, 270=East) maps
    // directly to DEVS-FIRE windDegree which uses the same convention.
    const windDegree = params.windDirection ?? 180;

    // total_sim_time (seconds) = stepInterval × totalSteps
    // Defaults: 10 steps of 360 s each = 3600 s (1 hour)
    const stepInterval = params.stepInterval ?? 360;
    const totalSteps   = params.totalSteps   ?? 10;
    const totalSimTime = stepInterval * totalSteps;

    return {
      info_type:              'simulation',
      cellResolution:         30,
      cellSpaceDimension:     GRID,
      cellSpaceDimensionLat:  GRID,
      team_num:               1,
      total_sim_time:         totalSimTime,
      windSpeed,
      windDegree,
      team_infos: [
        {
          team_name: 'team0',
          info_num:  1,
          details: [
            {
              type:     'segment',
              start_x:  cx - 2,
              start_y:  cy,
              end_x:    cx + 2,
              end_y:    cy,
              speed:    0.6,
              mode:     'continuous',
              distance: null,
            },
          ],
        },
      ],
      sup_infos:             [],
      sup_num:               0,
      // EPSG:5070 (Albers) coordinates for Atlanta area – same as DEVS-FIRE sample
      proj_center_lat:       1526271.822562622,
      proj_center_lng:       -35619.017015608770,
      fuel_data_adjusted:    [],
      aspect_data_adjusted:  [],
      slope_data_adjusted:   [],
    };
  }

  /**
   * runSimulationJWT
   * POST /simulation with Bearer token. Parses the array of
   * { op: "BURNING", x: col, y: row } events into a SimulationResult.
   */
  async runSimulationJWT(
    jwtToken: string,
    plan: Record<string, unknown>
  ): Promise<SimulationResult> {
    const res = await this.fetchWithTimeout(`${this.baseUrl}/simulation`, {
      method: 'POST',
      headers: {
        'Content-Type':  'application/json',
        'Authorization': `Bearer ${jwtToken}`,
      },
      body: JSON.stringify(plan),
    });

    if (!res.ok) {
      const body = await res.text();
      throw new Error(`[DevsFireClient] POST /simulation failed (${res.status}): ${body}`);
    }

    type BurningEvent = { op: string; x: number; y: number };
    const events = (await res.json()) as BurningEvent[];

    const burning = events.filter((e) => e.op === 'BURNING');
    const gridSize = (plan.cellSpaceDimension as number) ?? 200;

    // Use event array index as a proxy for simulation time (chronological order)
    const thermalGrid: ThermalCell[] = burning.map((e, i) => ({
      col:              e.x,
      row:              e.y,
      intensity:        1.0,
      timeOffsetSeconds: i,
    }));

    console.info(`[DevsFireClient] Simulation complete. ${burning.length} burning cells.`);

    return {
      sessionId:  'jwt-session',
      status:     'completed',
      thermalGrid,
      gridWidth:  gridSize,
      gridHeight: gridSize,
      summary:    `DEVS-FIRE simulation complete — ${burning.length} burning cells recorded.`,
    };
  }

  // ── DEVS-FIRE result parsers ──────────────────────────────────────────────

  /**
   * parseDevsFireBurningCells
   * Converts the raw DEVS-FIRE burning-cells result string into a typed
   * ThermalCell array for the frontend renderer.
   *
   * DEVS-FIRE returns a string of (cellId, ignitionTime) pairs. Supported
   * delimiters between pairs: space, semicolon, or newline.
   * Supported separators within a pair: comma or colon.
   *
   * Cell ID → (col, row) mapping:
   *   col = cellId % gridWidth
   *   row = Math.floor(cellId / gridWidth)
   *
   * @param raw           – Raw burning-cells string from the DEVS-FIRE API.
   * @param gridWidth     – Number of columns in the simulation grid.
   * @param gridHeight    – Number of rows in the simulation grid.
   * @param perimeterIds  – Optional Set of cell IDs on the fire perimeter.
   * @returns               Parsed ThermalCell array ready for the renderer.
   */
  private parseDevsFireBurningCells(
    raw: string,
    gridWidth: number,
    gridHeight: number,
    perimeterIds?: Set<number>
  ): ThermalCell[] {
    const cells: ThermalCell[] = [];

    // Split on whitespace, semicolons, or newlines to get individual pairs
    const pairs = raw.trim().split(/[\s;\n]+/);

    for (const pair of pairs) {
      if (!pair) continue;

      // Each pair is "cellId,ignitionTime" or "cellId:ignitionTime"
      const parts = pair.split(/[,:]/);
      if (parts.length < 2) continue;

      const cellId = parseInt(parts[0], 10);
      const ignitionTime = parseFloat(parts[1]);

      if (isNaN(cellId) || isNaN(ignitionTime)) continue;

      const col = cellId % gridWidth;
      const row = Math.floor(cellId / gridWidth);

      if (col < 0 || col >= gridWidth || row < 0 || row >= gridHeight) continue;

      cells.push({
        col,
        row,
        intensity: 1.0,
        timeOffsetSeconds: ignitionTime,
        isPerimeter: perimeterIds?.has(cellId) ?? false,
      });
    }

    return cells;
  }

  /**
   * parsePerimeterCellIds
   * Parses the DEVS-FIRE perimeter-cells string (space or comma-separated
   * integer cell IDs) into a typed number array.
   *
   * @param raw – Raw perimeter-cells string from the DEVS-FIRE API.
   * @returns    Array of integer cell IDs on the fire perimeter.
   */
  private parsePerimeterCellIds(raw: string): number[] {
    return raw
      .trim()
      .split(/[\s,;]+/)
      .map((s) => parseInt(s, 10))
      .filter((n) => !isNaN(n));
  }

  // ── Private helpers ─────────────────────────────────────────────────────────

  /**
   * withToken
   * Appends ?userToken=<token> to a URL as required by the DEVS-FIRE API.
   * All authenticated endpoints use this query-parameter pattern.
   *
   * @param url       – Base endpoint URL.
   * @param userToken – Dynamic session token to append.
   * @returns          Full URL with userToken query parameter.
   */
  private withToken(url: string, userToken: string): string {
    return `${url}?userToken=${encodeURIComponent(userToken)}`;
  }

  /**
   * buildHeaders
   * Returns the minimal headers required for DEVS-FIRE requests.
   * No Authorization header is used – auth is handled via ?userToken= instead.
   */
  private buildHeaders(): Record<string, string> {
    return {
      'Content-Type': 'application/json',
    };
  }

  /**
   * fetchWithTimeout
   * Wraps fetch with an AbortController-based timeout so hung DEVS-FIRE
   * requests don't block the Express event loop indefinitely.
   */
  private async fetchWithTimeout(url: string, options: RequestInit): Promise<Response> {
    const controller = new AbortController();
    const timeoutId = setTimeout(() => controller.abort(), this.timeoutMs);

    try {
      const response = await fetch(url, { ...options, signal: controller.signal });
      return response;
    } catch (err) {
      // Distinguish a timeout abort from any other network error
      if (err instanceof Error && err.name === 'AbortError') {
        throw new Error(
          `[DevsFireClient] Request to ${url} timed out after ${this.timeoutMs / 1000}s. ` +
          `Check that DEVS_FIRE_BASE_URL is reachable.`
        );
      }
      throw err;
    } finally {
      clearTimeout(timeoutId);
    }
  }

  /**
   * sleep
   * Returns a Promise that resolves after the specified delay.
   * Used to pace the simulation result polling loop.
   */
  private sleep(ms: number): Promise<void> {
    return new Promise((resolve) => setTimeout(resolve, ms));
  }
}
